- README.md
- app_opener/README.md
- app_opener/app_opener.sh
This is a script to open my usual applications on PC startup. It just saves me a few clicks whenever I restart my PC.
The script however simple, might spark some ideas for automating your own work environment.
1. Make sure your file is [marked as executable](https://askubuntu.com/a/229592/860015)
2. Add the script to your [startup applications](https://askubuntu.com/a/719157/860015)
___
> add app_opener

- README.md
- ad_change_check/README.md
- ad_change_check/ad_change_check.ps1
Added Powershell script to check if changes have been made to specified Active Directory objects
> Added ad_change_check

- image_resize/README.md
- image_resize/index.html
You can make use of image resize/compression while uploading images in web app.
> Added Image Resize in super-scripts

- README.md
- folder_autosync/README.md
- folder_autosync/autosync.sh
- folder_autosync/stopsync.sh
Hello, I wrote some scripts for automatically syncing a local folder with a remote folder(via ssh)
This is very useful when we're restricted to use certain virtual machine/os through ssh for running a project (i.e we can sync the project folder so that we can write code on our laptop and be able to run it in the remote machine)
> folder autosync script

- README.md
- video_length_calculator/README.md
- video_length_calculator/video_length
A script to calculate all mp4 video length's in the current directory.
> Script: Calculate Video Length

- README.md
- raw_to_jpeg/README.md
- raw_to_jpeg/raw_to_jpeg.sh
A script to convert raw images to jpeg format
> added raw_to_jpeg

- README.md
- loop_command/README.md
- loop_command/multi_exec.sh
Just executes n times a given command
> Loop command

- README.md
Updated as asked by the owner of the repository as reviewed in response to pullrequest #58
> Updated the README file of root as asked.

- README.md
- rename_images_exif_date/README.md
- rename_images_exif_date/rename_images_exif_date.sh
Simple script to rename .jpg files with the creation date in its metada
> Script to rename JPG images with the creation date in the metadata

- README.md
- scrape_googlemaps_search_data/README.md
- scrape_googlemaps_search_data/get_data.py
#1 selenium script to scrape details of a place/search result of google search that saves the name, phone number, email and website
> Googlemaps scraper

- README.md
- create_whatsapp_group/README.md
- create_whatsapp_group/create_group.py
#1 
* creates whatsapp group with contacts as a list in code.
* uses selenium
> Create whatsapp group

- README.md
- bootstrap_mac_dev_env/README.md
- bootstrap_mac_dev_env/bootstrap.sh
Pure Bash script to get up & running on new Mac for Python development. Instructions and Readme filled out
> Bootstrap Mac Development Environment

- README.md
- linux_lock_with_usb_protection/README.md
- linux_lock_with_usb_protection/lock
- linux_lock_with_usb_protection/usblistener.py
This is a small script I use for protecting my usb ports (useful if I leave my laptop around without supervision in the office).
Of course other locking tools can be used, I just happen to have `i3lock` :)
> Add script for linux lock with usb protection

- README.md
- mouse_keyboard_automator/README.md
- mouse_keyboard_automator/main.py
Added new script
Also fixed README
> Added mouse_keyboard_automator

- prod_server_config/README.md
- prod_server_config/execute.py
- prod_server_config/install_ssl.py
- prod_server_config/nginx.py
This is a script to automatically set up a simple nginx server for your website
> Scripts for setting up production web server

- operation on arrays/README.md
- operation on arrays/run.py
ui based operations on arrays :)
> added script

- bg-changer/BC.py
- bg-changer/BC2.py
- bg-changer/README.txt
changes background periodically as mentioned in the commit log
> added bg-changer

- clustering_and_regression/README.md
- clustering_and_regression/algorithms.py
Added regression and clustering methods to help with data analytics
> Added regression and automatic clustering with sklearn

- wallpaper_downloader/README.md
- wallpaper_downloader/alpha_downloader.py
The above script downloads wallpapers from alphacoders.com
> Added script to download wallpapers

- README.md
- git_email_change/README.md
- git_email_change/git_email_change.py
- crawls through a given folder
- updates the git email from work email to personal email
- This helps to avoid comitting to a personal Repo with a work email
> Git change email

- CONTRIBUTING.md
> adding contributing guidelines

- CONTRIBUTING.md
- new details
- some more rules
> updating contributing guidelines

- xor_encrypt_decrypt_txt/README.md
- xor_encrypt_decrypt_txt/xor_encrypt_decrypt.py
Added Python script that allows to xor_excrypt/decrypt .txt file.
> Xor encrypt decrypt by potyoma

- web_scrapper_imdb/180110045_Mridul_Agrawal.py
- web_scrapper_imdb/readme.md
Adding a script to scrape the top 250 movies from IMDB website
> Web scrapping code for IMDB website

- automated_steamVR_startup/README.md
- automated_steamVR_startup/start_vr.bat
This is a file I programmed to automatically open Steam and then SteamVR. I intend it to be the kind of program you start and then leave your computer to go put on the headset. It saves a bit of time waiting for Steam and then SteamVR to open manually.
> Add Automated SteamVR Startup batch file

- README.md
- youtube_playlist_to_mp3/README.md
- youtube_playlist_to_mp3/youtube_mp3.py
> Adding a script to download a youtube playlist as mp3 files.

- facebook_scrapper/README.md
- facebook_scrapper/facebook_scraper.py
This is a simple python3 script used to download a user's friend list from facebook. The script uses selenium & Firefox to automate the login process and extract the data from the user's account. All you have to do is to write the email and password and the script will do all the work. Simple!
> facebook-scrapper

- google-form/README.md
- google-form/automate_google_form.py
Any google form automation with bypass of captacha and bot analyzer of browser that too infinite number of times of submit will be allowed.
> Google form automation

- search_clipboard_movie/README.md
- search_clipboard_movie/movieseek.py
Signed-off-by: Dhiman Seal <furyx.ds@gmail.com>
> Added my online Movie Finding script.

- .gitignore
- should-i-run-it/README.md
- should-i-run-it/my-project-dir/data.json
- should-i-run-it/my-project-dir/index.js
- should-i-run-it/package.json
- should-i-run-it/should-i-run-it.js
I use this script a lot, it's really useful. :+1: :100:
> NodeJs: Added "Should I run it" script

- chat_bot/README.md
- chat_bot/intents.json
- chat_bot/main.py
> A bot to chat with when bored

- tic_tac_toe_game/readme_xo_game.txt
- tic_tac_toe_game/tic_tac_toe.py
I have added a game Tic-Tac-Toe created completely using Python logics. Readme will give a even more clear description
> Added a game - Tic Tac Toe

- TinderBot_automating_likes/README.md
- TinderBot_automating_likes/tinderBot.py
This script uses Selenium to automate the process of liking on Tinder.
> Add an automation that will automate Tinder likes

- wikipediaSearch/readme.md
- wikipediaSearch/wikipediaSearch.py
It uses wikipedia module to perform a search its very handly to have
> added an wikipedia search module

- propose_ur_bae/main.cpp
- propose_ur_bae/readme.md
If you want to propose ur bae and you too shy to say in front of ur bae, u can use this :))
> Add propose_ur_bae

- nasa_events_api/Categories_ID.json
- nasa_events_api/README.md
- nasa_events_api/app.py
> Adds Nasa Events API project

- weather_logger/README.md
- weather_logger/database.xml
- weather_logger/requirements.txt
- weather_logger/weather_logger.py
Adding a new python script per #111 which goes out and pulls current weather conditions.
> Adding weather_logger script

- get_university_courses/main.py
- get_university_courses/readme.md
Gets all available university (Minnesota State University, Mankato) courses
> University courses

- linkedin_followes_scraper/README.md
- linkedin_followes_scraper/linkedin_followers_scraper.py
This python automation script logs into your LinkedIn account, scrapes the names of your followers and adds them to an excel sheet. If the script is run for the first time, it creates a new excel sheet, otherwise adds to the next column of the previously created sheet, along with the date. Also, it compares current names to the ones in the previous column (if present) to check if you have lost or gained any followers, and highlights their names them with red and green text respectively.
> Added LinkedIn Followers Scraper

- Toonify/README.md
- Toonify/toonify-API-1.py
- Toonify/toonify-API-2.py
- Toonify/toonify-opencv.py
Added three python scripts to cartoonify any image or face:
- using opencv (though it doesn't gives great result😅)
- using toonify-API ( for local images )
- using toonify-API ( for urls )
Also added a README to give a brief overview of how to work with these scripts
> Cartoonify Script

- emoji/README.md
- emoji/emoji.sh
- emoji/emoji_list
This script lets you get emojis quickly from the large emoji list.
> Hacktoberfest 2019: Added to script to get emojis

- pythonGMailReader/pythonGMailReader.py
- pythonGMailReader/readme.txt
EZ and PZ email reader with Python 3.
> Reading Emails

- unix_time_converter/README.md
- unix_time_converter/unix_time_converter.py
I'm adding a python script to convert a unix timestamp to a human readable format.
> Add a python script for converting a unix timestamp to human readable format

- insta_dp_downloader/README.md
- insta_dp_downloader/package-lock.json
- insta_dp_downloader/package.json
- insta_dp_downloader/script.js
add insta_dp_downloader node based script
node script your_insta_username
that download your dp and display followers status
> add Insta_dp_downloader script

- convert_png_to_jpg/README.md
- convert_png_to_jpg/convert.py
Add simple script to convert png to jpg image!
> Add script to convert png to jpg image

- image_to_b64/Readme.md
- image_to_b64/convert.py
Add my simple script to convert image to base64 or the other way around!
> Add image to b64 encoder/decoder

- scripts/Scheduled_Program_Killer/README.md
- scripts/Scheduled_Program_Killer/cancelled.cmd
- scripts/Scheduled_Program_Killer/schtasks.cmd
Added folder for script that force quits any user specified program with a set scheduler.
Instruction provided in README.md
> added schedule program killer
